name: Check all
on:
  pull_request:
jobs:
  check-all:
    runs-on: ubuntu-latest
    environment: tests
    timeout-minutes: 30
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Check Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Check types
        run: yarn types

      - name: Run Unit Tests
        run: yarn test:unit

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Integration Tests
        env:
          EL_URL: ${{ secrets.EL_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          VAULT_ADDRESS: ${{ vars.VAULT_ADDRESS }}
          CHAIN_ID: ${{ vars.CHAIN_ID }}
          FORK_BLOCK_NUMBER: ${{ vars.FORK_BLOCK_NUMBER }}
          DEPLOYED: ${{ vars.DEPLOYED }}
          ANVIL_PORT: 8545
          NODE_ENV: test
          VITEST: true
        run: yarn test:integration
