name: Publish Dry Run
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      NPM_TOKEN:
        description: "NPM token"
        required: true

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  publish-dry-run:
    runs-on: ubuntu-latest
    environment: pre-publish
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Dry run Publish
        run: |
          yarn semantic-release --dry-run --silent > /tmp/semantic-release-output
          grep -E '#|###|\*' /tmp/semantic-release-output > dry_run_output.txt || [ $? -eq 1 ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Write results to summary
        run: |
          if [ -s dry_run_output.txt ]; then
            echo "# Packages to be published:" >> $GITHUB_STEP_SUMMARY
            cat dry_run_output.txt >> $GITHUB_STEP_SUMMARY
          else
            echo "Nothing will be published" >> $GITHUB_STEP_SUMMARY
          fi
